name: CI - Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          echo "Rodando testes no ambiente DEV"
          pytest || echo "Sem testes ainda..."

      - name: Simular Deploy
        run: echo "Deploy automático para ambiente PROD (simulado)"
